a = 5  #integer
b = 5.5 #float
c = 1+2j #complex
d = "Hello" #string
e = [1,2,3,4] #list
f = (1,2,3,4) #tuple
g = {1,2,3,4} #set
h = {1:"one", 2:"two", 3:"three"} #dictionary
i = True #boolean
j = None #none
k = bytes(5) #bytes
l = bytearray(5) #bytearray
m = memoryview(bytes(5)) #memoryview
n = range(5) #range
o = frozenset({1,2,3,4}) #frozenset
p = complex(1,2) #complex
q = dict({1:"one", 2:"two", 3:"three"}) #dict
r = list((1,2,3,4)) #list
s = tuple((1,2,3,4)) #tuple
t = set((1,2,3,4)) #set
u = str("Hello") #string
v = int(5) #integer
w = float(5.5) #float
x = bool(True) #boolean
